// <auto-generated />
using System;
using DbUpdater.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DbUpdater.Migrations
{
    [DbContext(typeof(EcoDb))]
    partial class EcoDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DbUpdater.Models.WaterRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Depth")
                        .HasColumnType("double precision");

                    b.Property<string>("ParameterCode")
                        .HasColumnType("text");

                    b.Property<DateTime>("SampleDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StationId")
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .HasColumnType("text");

                    b.Property<double?>("Value")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("StationId");

                    b.ToTable("WaterRecords", (string)null);
                });

            modelBuilder.Entity("DbUpdater.Models.WaterStation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CountryName")
                        .HasColumnType("text");

                    b.Property<string>("StationIdentifier")
                        .HasColumnType("text");

                    b.Property<string>("WaterBodyName")
                        .HasColumnType("text");

                    b.Property<string>("WaterType")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("WaterStations", (string)null);
                });

            modelBuilder.Entity("DbUpdater.Models.WeatherRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("WeatherRecords", (string)null);
                });

            modelBuilder.Entity("DbUpdater.Models.WaterRecord", b =>
                {
                    b.HasOne("DbUpdater.Models.WaterStation", "Station")
                        .WithMany("Measurements")
                        .HasForeignKey("StationId");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("DbUpdater.Models.WeatherRecord", b =>
                {
                    b.OwnsOne("DbUpdater.Models.Current", "Current", b1 =>
                        {
                            b1.Property<int>("WeatherRecordId")
                                .HasColumnType("integer");

                            b1.Property<int>("Cloud")
                                .HasColumnType("integer");

                            b1.Property<double>("FeelslikeC")
                                .HasColumnType("double precision")
                                .HasJsonPropertyName("feelslike_c");

                            b1.Property<double>("FeelslikeF")
                                .HasColumnType("double precision")
                                .HasJsonPropertyName("feelslike_f");

                            b1.Property<int>("Humidity")
                                .HasColumnType("integer");

                            b1.Property<int>("IsDay")
                                .HasColumnType("integer")
                                .HasJsonPropertyName("is_day");

                            b1.Property<string>("LastUpdated")
                                .HasColumnType("text")
                                .HasJsonPropertyName("last_updated");

                            b1.Property<long>("LastUpdatedEpoch")
                                .HasColumnType("bigint")
                                .HasJsonPropertyName("last_updated_epoch");

                            b1.Property<double>("PrecipIn")
                                .HasColumnType("double precision")
                                .HasJsonPropertyName("precip_in");

                            b1.Property<double>("PrecipMm")
                                .HasColumnType("double precision")
                                .HasJsonPropertyName("precip_mm");

                            b1.Property<double>("PressureIn")
                                .HasColumnType("double precision")
                                .HasJsonPropertyName("pressure_in");

                            b1.Property<double>("PressureMb")
                                .HasColumnType("double precision")
                                .HasJsonPropertyName("pressure_mb");

                            b1.Property<double>("TempC")
                                .HasColumnType("double precision")
                                .HasJsonPropertyName("temp_c");

                            b1.Property<double>("TempF")
                                .HasColumnType("double precision")
                                .HasJsonPropertyName("temp_f");

                            b1.Property<double>("Uv")
                                .HasColumnType("double precision")
                                .HasJsonPropertyName("uv");

                            b1.Property<int>("WindDegree")
                                .HasColumnType("integer")
                                .HasJsonPropertyName("wind_degree");

                            b1.Property<string>("WindDir")
                                .HasColumnType("text")
                                .HasJsonPropertyName("wind_dir");

                            b1.Property<double>("WindKph")
                                .HasColumnType("double precision")
                                .HasJsonPropertyName("wind_kph");

                            b1.Property<double>("WindMph")
                                .HasColumnType("double precision")
                                .HasJsonPropertyName("wind_mph");

                            b1.HasKey("WeatherRecordId");

                            b1.ToTable("WeatherRecords", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("WeatherRecordId");

                            b1.OwnsOne("DbUpdater.Models.AirQuality", "AirQuality", b2 =>
                                {
                                    b2.Property<int>("CurrentWeatherRecordId")
                                        .HasColumnType("integer");

                                    b2.Property<double>("Co")
                                        .HasColumnType("double precision");

                                    b2.Property<int>("GbDefraIndex")
                                        .HasColumnType("integer")
                                        .HasJsonPropertyName("gb-defra-index");

                                    b2.Property<double>("No2")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("O3")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("Pm10")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("Pm25")
                                        .HasColumnType("double precision")
                                        .HasJsonPropertyName("pm2_5");

                                    b2.Property<double>("So2")
                                        .HasColumnType("double precision");

                                    b2.Property<int>("UsEpaIndex")
                                        .HasColumnType("integer")
                                        .HasJsonPropertyName("us-epa-index");

                                    b2.HasKey("CurrentWeatherRecordId");

                                    b2.ToTable("WeatherRecords", (string)null);

                                    b2.HasJsonPropertyName("air_quality");

                                    b2.WithOwner()
                                        .HasForeignKey("CurrentWeatherRecordId");
                                });

                            b1.OwnsOne("DbUpdater.Models.Condition", "Condition", b2 =>
                                {
                                    b2.Property<int>("CurrentWeatherRecordId")
                                        .HasColumnType("integer");

                                    b2.Property<int>("Code")
                                        .HasColumnType("integer");

                                    b2.Property<string>("Icon")
                                        .HasColumnType("text");

                                    b2.Property<string>("Text")
                                        .HasColumnType("text");

                                    b2.HasKey("CurrentWeatherRecordId");

                                    b2.ToTable("WeatherRecords", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("CurrentWeatherRecordId");
                                });

                            b1.Navigation("AirQuality");

                            b1.Navigation("Condition");
                        });

                    b.OwnsOne("DbUpdater.Models.Location", "Location", b1 =>
                        {
                            b1.Property<int>("WeatherRecordId")
                                .HasColumnType("integer");

                            b1.Property<string>("Country")
                                .HasColumnType("text");

                            b1.Property<double>("Lat")
                                .HasColumnType("double precision");

                            b1.Property<string>("Localtime")
                                .HasColumnType("text");

                            b1.Property<long>("LocaltimeEpoch")
                                .HasColumnType("bigint")
                                .HasJsonPropertyName("localtime_epoch");

                            b1.Property<double>("Lon")
                                .HasColumnType("double precision");

                            b1.Property<string>("Name")
                                .HasColumnType("text");

                            b1.Property<string>("Region")
                                .HasColumnType("text");

                            b1.Property<string>("TzId")
                                .HasColumnType("text")
                                .HasJsonPropertyName("tz_id");

                            b1.HasKey("WeatherRecordId");

                            b1.ToTable("WeatherRecords", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("WeatherRecordId");
                        });

                    b.Navigation("Current");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("DbUpdater.Models.WaterStation", b =>
                {
                    b.Navigation("Measurements");
                });
#pragma warning restore 612, 618
        }
    }
}
